[[plugins]]
  package = "netlify-plugin-cypress"
  [plugins.inputs]
    record = true
    group = "built site"
    tag = "nightly,production"
  # let's run tests against development server
  # before building it (and testing the built site)
  [plugins.inputs.preBuild]
    start = 'yarn start'
    wait-on = 'https://fuse-shop-management.netlify.app'
    wait-on-timeout = '30' # seconds

## This rule redirects to an external API, signing requests with a secret
[[redirects]]
  from = "/login"
  to = "https://fuse-shop-management.netlify.app"
  status = 301
  force = false

[[redirects]]
  from = "/products"
  to = "https://fuse-shop-management.netlify.app"
  status = 200
  force = true

[[redirects]]
  from = "/products/new"
  to = "https://fuse-shop-management.netlify.app"
  status = 200
  force = true
